PLUGIN_NAME: str = 'PowerPlayProgress'
plugin_version: str = '0.9.12'
mined_heading: str = "Mined:"

# rare_goods is now a dict mapping symbol to a dict with 'symbol' and 'name'
rare_goods = {
    "saxonwine": {"symbol": "saxonwine", "name": "Saxon Wine"},
    "rusanioldsmokey": {"symbol": "rusanioldsmokey", "name": "Rusani Old Smokey"},
    "thrutiscream": {"symbol": "thrutiscream", "name": "Thrutis Cream"},
    "uzumokulowgwings": {"symbol": "uzumokulowgwings", "name": "Uzumoku Low-G Wings"},
    "damnacarapaces": {"symbol": "damnacarapaces", "name": "Damna Carapaces"},
    "bastsnakegin": {"symbol": "bastsnakegin", "name": "Bast Snake Gin"},
    "terramaterbloodbores": {"symbol": "terramaterbloodbores", "name": "Terra Mater Blood Bores"},
    "livehecateseaworms": {"symbol": "livehecateseaworms", "name": "Live Hecate Sea Worms"},
    "gerasiangueuzebeer": {"symbol": "gerasiangueuzebeer", "name": "Gerasiangueuze Beer"},
    "chameleoncloth": {"symbol": "chameleoncloth", "name": "Chameleon Cloth"},
    "onionheadalphastrain": {"symbol": "onionheadalphastrain", "name": "Onionhead Alpha Strain"},
    "wolffesh": {"symbol": "wolffesh", "name": "Wolf Fesh"},
    "hipprotosquid": {"symbol": "hipprotosquid", "name": "Hippo Trot Squid"},
    "momusbogspaniel": {"symbol": "momusbogspaniel", "name": "Momus Bog Spaniel"},
    "taurichimes": {"symbol": "taurichimes", "name": "Tauri Chimes"},
    "fujintea": {"symbol": "fujintea", "name": "Fujin Tea"},
    "ethgrezeteabuds": {"symbol": "ethgrezeteabuds", "name": "Ethgreze Tea Buds"},
    "esusekucaviar": {"symbol": "esusekucaviar", "name": "Esuseku Caviar"},
    "zeesszeantgrubglue": {"symbol": "zeesszeantgrubglue", "name": "Zeesszean Grub Glue"},
    "azcancriformula42": {"symbol": "azcancriformula42", "name": "Azcancri Formula 42"},
    "witchhaulkobebeef": {"symbol": "witchhaulkobebeef", "name": "Witchhaul Kobe Beef"},
    "eraninpearlwhisky": {"symbol": "eraninpearlwhisky", "name": "Eranin Pearl Whisky"},
    "pantaaprayersticks": {"symbol": "pantaaprayersticks", "name": "Pantaa Prayer Sticks"},
    "konggaale": {"symbol": "konggaale", "name": "Kongga Ale"},
    "tiegfriessynthsilk": {"symbol": "tiegfriessynthsilk", "name": "Tiegfries Synth Silk"},
    "voidextractcoffee": {"symbol": "voidextractcoffee", "name": "Void Extract Coffee"},
    "vherculisbodyrub": {"symbol": "vherculisbodyrub", "name": "Vherculis Body Rub"},
    "vegaslimweed": {"symbol": "vegaslimweed", "name": "Vega Slimweed"},
    "honestypills": {"symbol": "honestypills", "name": "Honesty Pills"},
    "haidenblackbrew": {"symbol": "haidenblackbrew", "name": "Haiden Black Brew"},
    "nanomedicines": {"symbol": "nanomedicines", "name": "Nanomedicines"},
    "bankiamphibiousleather": {"symbol": "bankiamphibiousleather", "name": "Banki Amphibious Leather"},
    "chateaudeaegaeon": {"symbol": "chateaudeaegaeon", "name": "Chateau de Aegaeon"},
    "aganipperush": {"symbol": "aganipperush", "name": "Aganippe Rush"},
    "thehuttonmug": {"symbol": "thehuttonmug", "name": "The Hutton Mug"},
    "centaurimegagin": {"symbol": "centaurimegagin", "name": "Centauri Mega Gin"},
    "altairianskin": {"symbol": "altairianskin", "name": "Altairian Skin"},
    "cherbonesbloodcrystals": {"symbol": "cherbonesbloodcrystals", "name": "Cherbones Blood Crystals"},
    "jotunmookah": {"symbol": "jotunmookah", "name": "Jotun Mookah"},
    "gilyasignatureweapons": {"symbol": "gilyasignatureweapons", "name": "Gilya Signature Weapons"},
    "indibourbon": {"symbol": "indibourbon", "name": "Indi Bourbon"},
    "havasupaidreamcatcher": {"symbol": "havasupaidreamcatcher", "name": "Havasupai Dreamcatcher"},
    "buckyballbeermats": {"symbol": "buckyballbeermats", "name": "Buckyball Beer Mats"},
    "hip10175bushmeat": {"symbol": "hip10175bushmeat", "name": "HIP 10175 Bush Meat"},
    "ochoengchillies": {"symbol": "ochoengchillies", "name": "Ochoeng Chillies"},
    "ophiuchexinoartefacts": {"symbol": "ophiuchexinoartefacts", "name": "Ophiuch Exino Artefacts"},
    "mechucoshightea": {"symbol": "mechucoshightea", "name": "Mechucos High Tea"},
    "pavoniseargrubs": {"symbol": "pavoniseargrubs", "name": "Pavonis Ear Grubs"},
    "crystallinespheres": {"symbol": "crystallinespheres", "name": "Crystalline Spheres"},
    "lyraeweed": {"symbol": "lyraeweed", "name": "Lyrae Weed"},
    "hiporganophosphates": {"symbol": "hiporganophosphates", "name": "HIP Organophosphates"},
    "borasetanipathogenetics": {"symbol": "borasetanipathogenetics", "name": "Borasetani Pathogenetics"},
    "volkhabbeedrones": {"symbol": "volkhabbeedrones", "name": "Volkhab Bee Drones"},
    "wulpahyperboresystems": {"symbol": "wulpahyperboresystems", "name": "Wulpa Hyperbore Systems"},
    "motronaexperiencejelly": {"symbol": "motronaexperiencejelly", "name": "Motrona Experience Jelly"},
    "lucanonionhead": {"symbol": "lucanonionhead", "name": "Lucan Onionhead"},
    "tanmarktranquiltea": {"symbol": "tanmarktranquiltea", "name": "Tanmark Tranquil Tea"},
    "onionhead": {"symbol": "onionhead", "name": "Onionhead"},
    "tarachspice": {"symbol": "tarachspice", "name": "Tarach Spice"},
    "masterchefs": {"symbol": "masterchefs", "name": "Master Chefs"},
    "xihecompanions": {"symbol": "xihecompanions", "name": "Xihe Biomorphic Companions"},
    "mulachigiantfungus": {"symbol": "mulachigiantfungus", "name": "Mulachi Giant Fungus"},
    "tiolcewaste2pasteunits": {"symbol": "tiolcewaste2pasteunits", "name": "Tiolce Waste2Paste Units"},
    "neritusberries": {"symbol": "neritusberries", "name": "Neritus Berries"},
    "chieridanimarinepaste": {"symbol": "chieridanimarinepaste", "name": "Chieridani Marine Paste"},
    "ltthypersweet": {"symbol": "ltthypersweet", "name": "LTT Hypersweet"},
    "medbstarlube": {"symbol": "medbstarlube", "name": "Medb Star Lube"},
    "alyabodysoap": {"symbol": "alyabodysoap", "name": "Alya Body Soap"},
    "galactictravelguide": {"symbol": "galactictravelguide", "name": "Galactic Travel Guide"},
    "cromsilverfesh": {"symbol": "cromsilverfesh", "name": "Crom Silver Fesh"},
    "duradrives": {"symbol": "duradrives", "name": "Dura Drives"},
    "alacarakmoskinart": {"symbol": "alacarakmoskinart", "name": "Alacarakmo Skin Art"},
    "rajukrumultistoves": {"symbol": "rajukrumultistoves", "name": "Rajukru Multi Stoves"},
    "cetirabbits": {"symbol": "cetirabbits", "name": "Ceti Rabbits"},
    "aepyornisegg": {"symbol": "aepyornisegg", "name": "Aepyornis Egg"},
    "ngunamodernantiques": {"symbol": "ngunamodernantiques", "name": "Nguna Modern Antiques"},
    "mokojingbeastfeast": {"symbol": "mokojingbeastfeast", "name": "Mokojing Beast Feast"},
    "thewatersofshintara": {"symbol": "thewatersofshintara", "name": "The Waters of Shintara"},
    "ultracompactprocessorprototypes": {"symbol": "ultracompactprocessorprototypes", "name": "Ultra Compact Processor Prototypes"},
    "kachiriginfilterleeches": {"symbol": "kachiriginfilterleeches", "name": "Kachirigin Filter Leeches"},
    "utgaroarmillennialeggs": {"symbol": "utgaroarmillennialeggs", "name": "Utgaroar Millennial Eggs"},
    "helvetitjpearls": {"symbol": "helvetitjpearls", "name": "Helvetitj Pearls"},
    "ceremonialheiketea": {"symbol": "ceremonialheiketea", "name": "Ceremonial Heike Tea"},
    "vidavantianlace": {"symbol": "vidavantianlace", "name": "Vidavanti Anlace"},
    "bakedgreebles": {"symbol": "bakedgreebles", "name": "Baked Greebles"},
    "harmasilversearum": {"symbol": "harmasilversearum", "name": "Harmasilver Sea Rum"},
    "noneuclidianexotanks": {"symbol": "noneuclidianexotanks", "name": "Noneuclidian Exotanks"},
    "jaradharrepuzzlebox": {"symbol": "jaradharrepuzzlebox", "name": "Jaradharre Puzzle Box"},
    "coquimspongiformvictuals": {"symbol": "coquimspongiformvictuals", "name": "Coquim Spongiform Victuals"},
    "onionheadbetastrain": {"symbol": "onionheadbetastrain", "name": "Onionhead Beta Strain"},
    "albinoquechuamammothmeat": {"symbol": "albinoquechuamammothmeat", "name": "Albino Quechua Mammoth Meat"},
    "karetiicouture": {"symbol": "karetiicouture", "name": "Karetii Couture"},
    "korokungpellets": {"symbol": "korokungpellets", "name": "Korokung Pellets"},
    "aroucaconventualsweets": {"symbol": "aroucaconventualsweets", "name": "Arouca Conventual Sweets"},
    "kamorinhistoricweapons": {"symbol": "kamorinhistoricweapons", "name": "Kamorinh Historic Weapons"},
    "belalansrayleather": {"symbol": "belalansrayleather", "name": "Belalan's Ray Leather"},
    "mukusubiichitinos": {"symbol": "mukusubiichitinos", "name": "Mukusubi Ichitinos"},
    "cd75kittenbrandcoffee": {"symbol": "cd75kittenbrandcoffee", "name": "CD75 Kitten Brand Coffee"},
    "shanscharisorchid": {"symbol": "shanscharisorchid", "name": "Shanscharis Orchid"},
    "vanayequirhinofur": {"symbol": "vanayequirhinofur", "name": "Vanayequi Ceratomorpha Fur"},
    "eleuthermals": {"symbol": "eleuthermals", "name": "Eleu Thermals"},
    "apavietii": {"symbol": "apavietii", "name": "Apa Vietii"},
    "deuringastruffles": {"symbol": "deuringastruffles", "name": "Deuringa Truffles"},
    "hip118311swarm": {"symbol": "hip118311swarm", "name": "HIP 118311 Swarm"},
    "giantverrix": {"symbol": "giantverrix", "name": "Giant Verrix"},
    "azuremilk": {"symbol": "azuremilk", "name": "Azure Milk"},
    "leestianeviljuice": {"symbol": "leestianeviljuice", "name": "Leestian Evil Juice"},
    "disomacorn": {"symbol": "disomacorn", "name": "Diso Ma Corn"},
    "uszaiantreegrub": {"symbol": "uszaiantreegrub", "name": "Uszaian Tree Grub"},
    "baltahsinevacuumkrill": {"symbol": "baltahsinevacuumkrill", "name": "Baltah'sine Vacuum Krill"},
    "lavianbrandy": {"symbol": "lavianbrandy", "name": "Lavian Brandy"},
    "orrerianviciousbrew": {"symbol": "orrerianviciousbrew", "name": "Orerian Vicious Brew"},
    "leatheryeggs": {"symbol": "leatheryeggs", "name": "Leathery Eggs"},
    "anynacoffee": {"symbol": "anynacoffee", "name": "Any Na Coffee"},
    "deltaphoenicispalms": {"symbol": "deltaphoenicispalms", "name": "Delta Phoenicis Palms"},
    "personalgifts": {"symbol": "personalgifts", "name": "Personal Gifts"},
    "edenapplesofaerial": {"symbol": "aerialedenapple", "name": "Eden Apples of Aerial"},
    "hr7221wheat": {"symbol": "hr7221wheat", "name": "HR 7221 Wheat"},
    "yasokondileaf": {"symbol": "yasokondileaf", "name": "Yasokondi Leaf"},
    "holvaduellingblades": {"symbol": "holvaduellingblades", "name": "Holva Duelling Blades"},
    "anduligafireworks": {"symbol": "anduligafireworks", "name": "Anduliga Fireworks"},
    "burnhambiledistillate": {"symbol": "burnhambiledistillate", "name": "Burnham Bile Distillate"},
    "kinagoviolins": {"symbol": "kinagoviolins", "name": "Kinago Violins"},
    "ngadandarifireopals": {"symbol": "ngadandarifireopals", "name": "Ngadandari Fire Opals"},
    "rapabaosnakeskins": {"symbol": "rapabaosnakeskins", "name": "Rapabaos Snake Skins"},
    "toxandjivirocide": {"symbol": "toxandjivirocide", "name": "Toxandji Virocide"},
    "kamitracigars": {"symbol": "kamitracigars", "name": "Kamitra Cigars"},
    "wuthielokufroth": {"symbol": "wuthielokufroth", "name": "Wuthieloku Froth"},
    "sanumadecorativemeat": {"symbol": "sanumadecorativemeat", "name": "Sanuma Decorative Meat"},
    "geawendancedust": {"symbol": "geawendancedust", "name": "Geawend Dance Dust"},
    "jarouarice": {"symbol": "jarouarice", "name": "Jaroua Rice"},
    "giantirukamasnails": {"symbol": "giantirukamasnails", "name": "Giant Irukama Snails"},
    "classifiedexperimentalequipment": {"symbol": "classifiedexperimentalequipment", "name": "Classified Experimental Equipment"},
    "njangarisaddles": {"symbol": "njangarisaddles", "name": "Njangari Saddles"},
    "soontillrelics": {"symbol": "soontillrelics", "name": "Soontill Relics"},
    "gomanyauponcoffee": {"symbol": "gomanyauponcoffee", "name": "	Goman Yaupon Coffee"},
    "karsukilocusts": {"symbol": "karsukilocusts", "name": "Karsuki Locusts"},
    "eshuumbrellas": {"symbol": "eshuumbrellas", "name": "Eshu Umbrellas"},
    "wheemetewheatcakes": {"symbol": "wheemetewheatcakes", "name": "Wheemete Wheat Cakes"},
    "sothiscrystallinegold": {"symbol": "sothiscrystallinegold", "name": "Sothis Crystalline Gold"},
    "jaquesquinentianstill": {"symbol": "jaquesquinentianstill", "name": "Jaques Quinentiant Still"},
    "tianveganmeat": {"symbol": "tianveganmeat", "name": "Tian Vegan Meat"},
    "sothiscrystallinegold": {"symbol": "sothiscrystallinegold", "name": "Sothis Crystalline Gold"},
    "sothiscrystallinesilver": {"symbol": "sothiscrystallinesilver", "name": "Sothis Crystalline Silver"},
    "sothiscrystallinelithium": {"symbol": "sothiscrystallinelithium", "name": "Sothis Crystalline Lithium"}
}